- hosts: loadbalancer
  gather_facts: True
  become: yes
  roles:
    - role: haproxy

  vars:
    haproxy:
      backends:
        - name: production
          balance: roundrobin
          servers:
            - name: web1
              address: 10.0.0.101
              port: 80
            - name: web2
              address: 10.0.0.102
              port: 80
