---
language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r haproxy/tests/test-requirements.txt
# command to run tests
script:
  - ansible --version
  - ansible-lint haproxy/tests/test.yml -v
  - ansible-playbook -i haproxy/tests/inventory haproxy/tests/test.yml --syntax-check
