---
# tasks file for haproxy
- name: Set Operating system specific variables
  include_vars: '{{ loop_vars }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - 'defaults.yml'
      paths:
        - 'vars'
  loop_control:
    loop_var: loop_vars
  tags:
    - variables

- name: Set Operating system specific tasks
  include_tasks: '{{ loop_operating_system }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - 'defaults.yml'
      paths:
        - 'operating_system'
  loop_control:
    loop_var: loop_operating_system
  tags:
    - setup
